### ISSUE TITLE
Vaccinated number not updating when data is downloaded to the tablet

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#295] opened 2018-03-15 13:55 UTC
Vaccinated number for Coverage Reports doesn't update when data for children registered in tablet A is downloaded to tablet B (User logs into tablet B with same credentials used in tablet A). The numbers only update after a user clears data from the ZEIR app in tablet B then logs back in with same credentials. 

**Steps to reproduce**
- Log into tablet A then register a child and record vaccines (BCG & OPV 0) for a certain month say March 2018. 
- Once data has synced to the server and the Vaccinated number for the Coverage Reports is updated accordingly, log into tablet B with same credentials. 
- After data has synced, check if the vaccinated number for the Coverage Reports is updated. 
- If not updated, clear app's data then check again after data has synced.

**Comment by keymane** [comment] 2018-03-29 10:59
@faith-mutua I'm not able to reproduce this bug. Are the vaccines synced to Tablet B? Then the coverage reports are generated after sync has completed. For example, if the sync interval for these reports is 5 minutes then they will be generated 5 minutes after the vaccines have been synced to Tablet B

**Comment by faith-mutua** [comment] 2018-04-09 09:41
@keymane yes, the vaccines are synced to Tablet B.  Seems like this is not an issue any more. I also couldn't replicate the bug on the latest debug apk v1.3.3

**Comment by cagulas** [comment] 2018-04-10 07:07
Closing this issue, since it cannot be reproduced in the latest apk.

**Closed by cagulas** 2018-04-10 07:07 UTC
Labels: Coverage Report, High Priority, bug
