### ISSUE TITLE
Add better handling for locations with more than one tag

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#36] opened 2017-09-08 07:49 UTC
_From @geoffreymuchai on May 24, 2017 18:9_

Locations with more than one tag cause the application to raise the following exception when trying to create the location hierarchy

Exception thrown:
``` java
05-24 18:53:54.670 6954-6954/org.ei.opensrp.path E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.ei.opensrp.path, PID: 6954
java.lang.NullPointerException: Attempt to read from field 'char[] java.lang.String.value' on a null object reference
     at java.lang.String.<init>(String.java:421)
     at util.JsonFormUtils.getOpenMrsReadableName(JsonFormUtils.java:1545)
     at org.ei.opensrp.path.view.LocationPickerView.init(LocationPickerView.java:93)
     at org.ei.opensrp.path.fragment.BaseSmartRegisterFragment.setupViews(BaseSmartRegisterFragment.java:94)
     at org.ei.opensrp.path.fragment.ChildSmartRegisterFragment.setupViews(ChildSmartRegisterFragment.java:206)
     at org.ei.opensrp.path.fragment.ChildSmartRegisterFragment.onCreateView(ChildSmartRegisterFragment.java:199)
     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
     at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:490)
     at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:141)
     at android.support.v4.view.ViewPager.populate(ViewPager.java:1105)
     at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
     at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
     at android.view.View.measure(View.java:17609)
     at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:868)
     at android.view.View.measure(View.java:17609)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5547)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
     at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
     at android.view.View.measure(View.java:17609)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5547)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
     at android.view.View.measure(View.java:17609)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5547)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
     at android.view.View.measure(View.java:17609)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5547)
     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
     at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
     at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
     at android.view.View.measure(View.java:17609)
     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5547)
     at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
     at android.view.View.measure(View.java:17609)
     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2082)
     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1217)
     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1423)
     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6186)
     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:793)
     at android.view.Choreographer.doCallbacks(Choreographer.java:606)
     at android.view.Choreographer.doFrame(Choreographer.java:575)
     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:779)
     at android.os.Handler.handleCallback(Handler.java:739)
     at android.os.Handler.dispatchMessage(Handler.java:95)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5601)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
 	at com.an
05-24 1
```

_Copied from original issue: OpenSRP/opensrp-client#516_

**Comment by cagulas** [comment] 2018-03-23 07:36
Closing, this is a duplicate of https://github.com/OpenSRP/opensrp-client-path/issues/190

**Closed by cagulas** 2018-03-23 07:36 UTC
Labels: PATH BID Zambia, bug
